/* Single source of truth for all publications, drawn on by /publications/ and by
   project pages that want to show a subset as boxes (see /js/publications.js).

   summary: lay-language description, one string per site language — left empty
   until written. abstract: the paper's own technical abstract, copied verbatim
   (English only, as originally published — not translated). */

window.PUBLICATIONS = [
  {
    id: "physics-professors-genai",
    year: 2026,
    firstAuthor: true,
    projects: ["learning-with-ai"],
    authors: "Skogvoll, V., &amp; Odden, T. O.",
    title: "How Physics Professors Use and Frame Generative AI Tools",
    venueHtml: "<em>European Journal of Physics</em>, 47(2), 025713",
    link: "https://doi.org/10.1088/1361-6404/ae55e0",
    linkLabel: "doi.org/10.1088/1361-6404/ae55e0",
    summary: { en: "", no: "", sv: "" },
    abstract: "Generative AI is rapidly reshaping how physicists teach, learn, and conduct research, yet little is known about how physics faculty are responding to these changes. We interviewed 12 physics professors at a major Scandinavian research university to explore their uses and perceptions of Generative AI (GenAI) in both teaching and research. Using the theoretical framework of epistemic framing, we conducted a thematic analysis that identified 19 overlapping practices, ranging from coding and literature review to assessment and feedback. From these practices, we derived six overlapping epistemic frames through which professors make sense of GenAI: as a threat to genuine learning and assessment, a source of knowledge, a discussion partner, a text-processing tool, a coding tool, and a labor-saving device. While the latter five position GenAI as a useful tool in the physicists' toolbox, the threat frame represented an overarching concern that colored all other frames. These findings reveal how GenAI is beginning to transform what it means to be a physicist, highlighting both opportunities for innovation and challenges for academic integrity and learning."
  },
  {
    id: "elastic-spinodal-instabilities",
    year: 2026,
    firstAuthor: false,
    images: ["/media/pub-elastic-spinodal-instabilities.png"],
    projects: ["phase-field-crystals"],
    authors: "Elder, K. R., Aaron, B., Skogvoll, V., &amp; Angheluta, L.",
    title: "Elastic and Spinodal Instabilities in Strained Periodic States: A Phase-Field-Crystal Study",
    venueHtml: "<em>Physical Review E</em>, 114(2), 024139",
    link: "https://doi.org/10.1103/19bb-bqcd",
    linkLabel: "doi.org/10.1103/19bb-bqcd",
    summary: { en: "", no: "", sv: "" },
    abstract: ""
  },
  {
    id: "laere-med-ki-mnt",
    year: 2025,
    firstAuthor: true,
    projects: ["learning-with-ai"],
    authors: "Skogvoll, V., &amp; Odden, T. O.",
    title: "Lære med Kunstig intelligens",
    venueHtml: "In <em>Artikkelsamling — MNT-konferansen 2025</em> (Vol. 9, No. 2, pp. 449–453)",
    link: "https://doi.org/10.5324/njsteme.v9i2.6403",
    linkLabel: "doi.org/10.5324/njsteme.v9i2.6403",
    summary: { en: "", no: "", sv: "" },
    abstract: ""
  },
  {
    id: "comfit-joss",
    year: 2024,
    firstAuthor: true,
    images: ["/media/pub-comfit-joss.png"],
    projects: ["phase-field-crystals"],
    authors: "Skogvoll, V., &amp; Rønning, J.",
    title: "ComFiT: A Python library for computational field theory with topological defects",
    venueHtml: "<em>Journal of Open Source Software</em>, 9(98), 6599",
    link: "https://doi.org/10.21105/joss.06599",
    linkLabel: "doi.org/10.21105/joss.06599",
    extraLinks: [{ href: "https://github.com/vidarsko/ComFiT", label: "View on GitHub" }],
    summary: { en: "", no: "", sv: "" },
    abstract: "Field theories described by partial differential equations (PDEs) are the backbone of many areas in physics. Examples of such field theories include the Navier-Stokes equations, which describe how air flows around the wing of an airplane; the Schrödinger equation, which governs how microscopic particles behave; Maxwell's equations, which explain the behavior of electromagnetic fields; and the Nobel Prize-winning Ginzburg-Landau theory, which explains how superconductors work. Despite their importance, simulating field theories often requires specialized software and programming expertise. Even though there exist specialized software packages like FEniCS for solving PDEs, these are often focused on numerical efficiency at the cost of legibility or user-friendliness and fall short in offering functionalities for visualizing and analyzing outcomes. In particular, in the realm of many field theories, the study of topological defects — small structures like vortices in fluids — is essential for understanding phenomena such as phase transitions, turbulence and pattern formation. Due to the shared mathematical structures of these topological defects, recent research has shown that a common computational framework can be used to study them across different physical systems, ranging from Bose-Einstein condensates to nematic liquid crystals and crystalline solids. However, a unified computational framework that brings all these systems together is lacking. ComFiT aims to close this gap, catering to both researchers and educators in physics, by providing a user-friendly, object-oriented framework for setting up a physical system, solving PDEs in one, two and three dimensions, visualizing results, and tracking topological defects. In so doing, ComFiT also brings advanced models of phase-field crystal modeling and nematic liquid crystals to the Python ecosystem, which are currently scarcely available in the open-source community, especially for three dimensions."
  },
  {
    id: "laere-fysikk-sprakmodeller",
    year: 2024,
    firstAuthor: true,
    images: ["/media/pub-laere-fysikk-sprakmodeller.png"],
    projects: ["learning-with-ai"],
    authors: "Skogvoll, V., &amp; Odden, T. O.",
    title: "Lære fysikk med språkmodeller",
    venueHtml: "<em>Fra Fysikkens Verden</em>",
    link: null,
    linkLabel: null,
    summary: { en: "", no: "", sv: "" },
    abstract: ""
  },
  {
    id: "unified-field-theory-defects",
    year: 2023,
    firstAuthor: true,
    images: ["/media/pub-unified-field-theory-defects.png"],
    projects: ["phase-field-crystals"],
    authors: "Skogvoll, V., Rønning, J., Salvalaglio, M., &amp; Angheluta, L.",
    title: "A unified field theory of topological defects and non-linear local excitations",
    venueHtml: "<em>Npj Computational Materials</em>, 9(1)",
    link: "https://doi.org/10.1038/s41524-023-01077-6",
    linkLabel: "doi.org/10.1038/s41524-023-01077-6",
    summary: { en: "", no: "", sv: "" },
    abstract: "Topological defects and smooth excitations determine the properties of systems showing collective order. We introduce a generic non-singular field theory that comprehensively describes defects and excitations in systems with O(n) broken rotational symmetry. Within this formalism, we explore fast events, such as defect nucleation/annihilation and dynamical phase transitions where the interplay between topological defects and non-linear excitations is particularly important. To highlight its versatility, we apply this formalism in the context of Bose-Einstein condensates, active nematics, and crystal lattices."
  },
  {
    id: "elastic-field-evaluation-pfc",
    year: 2023,
    firstAuthor: false,
    images: ["/media/pub-elastic-field-evaluation-pfc.png"],
    projects: ["phase-field-crystals"],
    authors: "Punke, M., Skogvoll, V., &amp; Salvalaglio, M.",
    title: "Evaluation of the elastic field in phase-field crystal simulations",
    venueHtml: "<em>PAMM</em>, 23(3), e202300213",
    link: "https://doi.org/10.1002/pamm.202300213",
    linkLabel: "doi.org/10.1002/pamm.202300213",
    summary: { en: "", no: "", sv: "" },
    abstract: "The phase-field crystal model (PFC) describes crystal structures at diffusive timescales through a periodic order parameter representing the atomic density. One of its main features is that it naturally incorporates elastic and plastic deformation. To correctly interpret numerical simulation results or devise extensions related to the elasticity description, it is important to have direct access to the elastic field. In this work, we discuss its evaluation in classical PFC models based on the Swift–Hohenberg energy functional. We consider approaches where the stress field can be derived from the microscopic density field (i.e., the order parameter) and a simple novel numerical routine is proposed. By numerical simulations, we demonstrate that it overcomes some limitations of currently used methods. Moreover, we shed light on the elasticity description conveyed by classical PFC models, characterizing a residual stress effect present at equilibrium. We show explicitly and discuss the evaluation of the elastic fields in prototypical representative cases involving an elastic inclusion, a grain boundary, and dislocations."
  },
  {
    id: "phd-thesis",
    year: 2023,
    firstAuthor: true,
    type: "thesis",
    images: ["/media/pub-phd-thesis.png"],
    projects: ["phase-field-crystals"],
    authors: "Skogvoll, V.",
    title: "Symmetry, topology, and crystal deformations: A phase-field crystal approach",
    venueHtml: "Doctoral thesis, University of Oslo",
    link: "https://www.duo.uio.no/handle/10852/102731",
    linkLabel: "duo.uio.no/handle/10852/102731",
    summary: { en: "", no: "", sv: "" },
    abstract: ""
  },
  {
    id: "pfc-dislocation-kinematics",
    year: 2022,
    firstAuthor: true,
    images: ["/media/pub-pfc-dislocation-kinematics.png"],
    projects: ["phase-field-crystals"],
    authors: "Skogvoll, V., Angheluta, L., Skaugen, A., Salvalaglio, M., &amp; Viñals, J.",
    title: "A phase field crystal theory of the kinematics of dislocation lines",
    venueHtml: "<em>Journal of the Mechanics and Physics of Solids</em>, 166, 104932",
    link: "https://doi.org/10.1016/j.jmps.2022.104932",
    linkLabel: "doi.org/10.1016/j.jmps.2022.104932",
    summary: { en: "", no: "", sv: "" },
    abstract: "We introduce a dislocation density tensor and derive its kinematic evolution law from a phase field description of crystal deformations in three dimensions. The phase field crystal (PFC) model is used to define the lattice distortion, including topological singularities, and the associated configurational stresses. We derive an exact expression for the velocity of dislocation line determined by the phase field evolution, and show that dislocation motion in the PFC is driven by a Peach-Koehler force. As is well known from earlier PFC model studies, the configurational stress is not divergence free for a general field configuration. Therefore, we also present a method (PFCMEq) to constrain the diffusive dynamics to mechanical equilibrium by adding an independent and integrable distortion so that the total resulting stress is divergence free. In the PFCMEq model, the far-field stress agrees very well with the predictions from continuum elasticity, while the near-field stress around the dislocation core is regularized by the smooth nature of the phase-field. We apply this framework to study the rate of shrinkage of an dislocation loop seeded in its glide plane."
  },
  {
    id: "hydrodynamic-pfc",
    year: 2022,
    firstAuthor: true,
    images: ["/media/pub-hydrodynamic-pfc.png"],
    projects: ["phase-field-crystals"],
    authors: "Skogvoll, V., Salvalaglio, M., &amp; Angheluta, L.",
    title: "Hydrodynamic phase field crystal approach to interfaces, dislocations and multi-grain networks",
    venueHtml: "<em>Modelling and Simulation in Materials Science and Engineering</em>",
    link: "https://doi.org/10.1088/1361-651X/ac9493",
    linkLabel: "doi.org/10.1088/1361-651X/ac9493",
    summary: { en: "", no: "", sv: "" },
    abstract: "We derive a phase field crystal model that couples the diffusive evolution of a microscopic structure with the fast dynamics of a macroscopic velocity field, explicitly accounting for the relaxation of elastic excitations. This model captures better than previous formulations the dynamics of complex interfaces and dislocations in single crystals as well as grain boundary migration in poly-crystals where the long-range elastic field is properly relaxed. The proposed model features a diffusivity that depends non-linearly on the local phase. It induces more localized interfaces between a disordered phase (liquid-like) and an ordered phase, e.g., stripes or crystal lattices. For stripes, the interface dynamics are shown to be strongly anisotropic. We also show that the model is able to evolve the classical PFC at mechanical equilibrium. However, in contrast to previous approaches, it is not restricted to a single-crystal configuration or small distortions from a fixed reference lattice. To showcase the capabilities of this approach, we consider a few examples, from the annihilation of dislocation loops in a single crystal at mechanical equilibrium to the relaxation of a microstructure including crystalline domains with different orientations and grain boundaries. During the self-annihilation of a mixed type dislocation loop (i.e., not shear or prismatic), long-range elastic effects cause the loop to move out of plane before the annihilation event."
  },
  {
    id: "stress-ordered-systems",
    year: 2021,
    firstAuthor: true,
    images: ["/media/pub-stress-ordered-systems.png"],
    projects: ["phase-field-crystals"],
    authors: "Skogvoll, V., Skaugen, A., &amp; Angheluta, L.",
    title: "Stress in ordered systems: Ginzburg-Landau-type density field theory",
    venueHtml: "<em>Physical Review B</em>, 103(22), 224107",
    link: "https://doi.org/10.1103/PhysRevB.103.224107",
    linkLabel: "doi.org/10.1103/PhysRevB.103.224107",
    summary: { en: "", no: "", sv: "" },
    abstract: "We present a theoretical method for deriving the stress tensor and elastic response of ordered systems within a Ginzburg-Landau type density field theory in the linear regime. This is based on spatially coarse graining the microscopic stress which is determined by the variation of a free energy with respect to mass displacements. We find simple expressions for the stress tensor for phase field crystal (PFC) models for different crystal symmetries in two and three dimensions. Using tetradic product sums of reciprocal lattice vectors, we calculate elastic constants and show that they are directly related to the symmetries of the reciprocal lattices. We also show that except for bcc lattices, there are regions of model parameters for which the elastic response is isotropic. The predicted elastic stress-strain curves are verified by numerical strain-controlled bulk and shear deformations. Since the method is independent of a reference state, it extends also to defected crystals. We exemplify this by considering an edge and screw dislocation in the simple cubic lattice."
  },
  {
    id: "dislocation-nucleation-pfc",
    year: 2021,
    firstAuthor: true,
    images: ["/media/pub-dislocation-nucleation-pfc.png"],
    projects: ["phase-field-crystals"],
    authors: "Skogvoll, V., Skaugen, A., Angheluta, L., &amp; Viñals, J.",
    title: "Dislocation nucleation in the phase-field crystal model",
    venueHtml: "<em>Physical Review B</em>, 103(1), 014107",
    link: "https://doi.org/10.1103/PhysRevB.103.014107",
    linkLabel: "doi.org/10.1103/PhysRevB.103.014107",
    summary: { en: "", no: "", sv: "" },
    abstract: "We use the phase-field crystal model to study nucleation of edge dislocations in two dimensions under an applied stress field. A dislocation dipole nucleates under the applied stress, consistent with Burgers vector conservation. The phase field correctly accounts for elastic energy storage prior to nucleation and for dissipative relaxation during the nucleation event. We show that a lattice incompatibility field is a sensitive diagnostic of the location of the nucleation event and of the Burgers vector and slip direction of the dislocations that will be nucleated above threshold. A direct calculation of the phase-field energy accurately correlates with the nucleation event, as signaled by the lattice incompatibility field. We show that a Schmid-like criterion concerning the resolved stress at the nucleation site correctly predicts the critical nucleation stress. Finally, we present preliminary results for a three-dimensional, bcc lattice. The phase field allows direct computation of the lattice incompatibility tensor for both dislocation lines and loops."
  },
  {
    id: "composite-fermion-basis",
    year: 2017,
    firstAuthor: true,
    images: ["/media/pub-composite-fermion-basis.png"],
    projects: [],
    authors: "Skogvoll, V., &amp; Liabøtrø, O.",
    title: "Composite fermion basis for M-component Bose gases",
    venueHtml: "<em>Journal of Physics A: Mathematical and Theoretical</em>, 50(40), 405301",
    link: "https://doi.org/10.1088/1751-8121/aa85f7",
    linkLabel: "doi.org/10.1088/1751-8121/aa85f7",
    summary: { en: "", no: "", sv: "" },
    abstract: "The composite fermion (CF) formalism produces wave functions that are not always linearly independent. This is especially so in the low angular momentum regime in the lowest Landau level, where a subclass of CF states, known as simple states, gives a good description of the low energy spectrum. For the two-component Bose gas, explicit bases avoiding the large number of redundant states have been found. We generalize one of these bases to the M-component Bose gas and prove its validity. We also show that the numbers of linearly independent simple states for different values of angular momentum are given by coefficients of q-multinomials."
  },
  {
    id: "masters-thesis",
    year: 2017,
    firstAuthor: true,
    type: "thesis",
    images: ["/media/pub-masters-thesis.png"],
    projects: [],
    authors: "Skogvoll, V.",
    title: "Three M-Species Generalizations for Rotating Bose Gases in the Lowest Landau Level",
    venueHtml: "Master's thesis, University of Oslo",
    link: "https://www.duo.uio.no/handle/10852/57548",
    linkLabel: "duo.uio.no/handle/10852/57548",
    summary: { en: "", no: "", sv: "" },
    abstract: ""
  }
];
